<link rel="stylesheet" type="text/css" href="../../source/css/styleGPIntegList.css">
<div id="titleModalGPInteg">
    <label id="integMainLbl">Integrantes </label>
</div>
<div id="mainContainerInteg">
    
    <div class="headContainerCalfAlumnos">
        <div class="headCommonAlumnos">
            <div>
                <p>Registro</p>
            </div>
            <div>
                <p>Apellidos</p>
            </div>
            <div>
                <p>Nombres</p>
            </div>
        </div>
        <div class="headCalf">
            <p>Puntajes / Calificaciones</p>
        </div>
    </div>

    <div class="submaincontainerIntegGP">
        <div class="IntegContainer CalfIntegMainContainer">
           <div class="integSubcontainer">
               <div class="alumnoCalfCommonRow">
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div><div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
                <div class="alumnoCalfCommonRow">
                    <div>
                        <p>Registro</p>
                    </div>
                    <div>
                        <p>Apellidos</p>
                    </div>
                    <div>
                        <p>Nombres</p>
                    </div>
                </div>
           </div>
           <div class="calfSubcontainer">
               <div class="calfCommonRow headCalfRow">
                   <div>
                       P1.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
                   <div>
                       P2.1
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
               <div class="calfCommonRow">
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
                   <div>
                       <p>90</p>
                       <p>90</p>
                   </div>
               </div>
           </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="../../source/js/appGPIntegList.js"></script>